# syntax=docker/dockerfile:1
# check=error=true

# Dockerfile development

ARG RUBY_VERSION=3.3.7
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ARG APP_PATH=/app/
WORKDIR $APP_PATH

COPY . $APP_PATH

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y git libjemalloc2 libvips sqlite3 build-essential libyaml-dev && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY Gemfile Gemfile.lock ./
RUN bundle install
